# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  cluster_rg: 'flex-vol-test'
  kube_cluster: 'flex-vol-test'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    helm version  
  displayName: 'Check helm version'
