# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  azureSubscriptionEndpoint: 7e0f0a94-6ee2-466d-a26a-55dc04de83c7
  azureResourceGroup: flex-vol-test
  kubernetesCluster: flex-vol-test

steps:
- task: Kubernetes@1
  displayName: 'kubectl get'
  inputs:
    connectionType: Azure Resource Manager
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureResourceGroup: '$(azureResourceGroup)'
    kubernetesCluster: '$(kubernetesCluster)'

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'
#   inputs:

# - script: |
#     helm version  
#     kubectl get pods --all-namespaces

#   displayName: 'Check helm version'
