# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - master

variables:
  azureResourceGroup: flex-vol-test
  kubernetesCluster: flex-vol-test
  kubernetesServiceEndpoint: helmdeploy

#https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes?view=azure-devops#kubernetes-service-connection
steps:
- task: HelmDeploy@0
  displayName: Helm list
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(kubernetesServiceEndpoint)
    command: ls
    arguments: --all
- task: CmdLine@2
  displayName: Helm repo update
  inputs:
    script: |
      helm repo add stable https://kubernetes-charts.storage.googleapis.com
      helm repo update
- task: HelmDeploy@0
  displayName: Helm install sysdig
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(kubernetesServiceEndpoint)
    namespace: kube-system
    command: install
    chartName: stable/sysdig
    releaseName: sysdig
    
   