# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - master

variables:
  azureResourceGroup: flex-vol-test
  kubernetesCluster: flex-vol-test
  kubernetesServiceEndpoint: helmdeploy

#https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes?view=azure-devops#kubernetes-service-connection
steps:
- task: HelmDeploy@0
  displayName: Helm list
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(kubernetesServiceEndpoint)
    command: ls
    arguments: --all
- task: CmdLine@2
  displayName: Helm repo update
  inputs:
    script: |
      helm repo add stable https://kubernetes-charts.storage.googleapis.com
      helm repo update
      ls /home/vsts/work/1/s
# - task: HelmDeploy@0
#   displayName: Helm install sysdig
#   inputs:
#     connectionType: Kubernetes Service Connection
#     kubernetesServiceEndpoint: $(kubernetesServiceEndpoint)
#     namespace: kube-system
#     command: install
#     chartName: stable/sysdig
#     releaseName: sysdig
#     arguments: --dry-run --version 1.7.2
#     valueFile: sysdig-values.yaml
# - task: CmdLine@2
#   displayName: Deleting clusterrole and clusterolebinding for sysdig
#   inputs:
#     script: |
#       kubectl delete ClusterRole sysdig
#       kubectl delete ClusterRoleBinding sysdig
- task: HelmDeploy@0
  displayName: Helm upgrade sysdig
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(kubernetesServiceEndpoint)
    namespace: kube-system
    command: upgrade
    chartName: stable/sysdig
    releaseName: sysdig
    install: true
    arguments: --dry-run --version 1.7.6 --force
    valueFile: sysdig-values.yaml

   