image:
  tag: 9.5.0
daemonset:
  updateStrategy:
    type: RollingUpdate
ebpf:
  enabled: true
resources:
  requests:
    cpu: 1
    memory: 4G
  limits:
    cpu: 1
    memory: 4G
priorityClassName: system-node-critical
sysdig:
  accessKey: b833cec2-225f-42e0-8101-5ff1b753af26
  settings:
    app_checks:
      - name: postgres
        enabled: false
    app_checks_enabled: true
    events:
      docker:
        image: none
        container:
          - oom
        network: none
        volume: none
    go_k8s_user_events: true
    log:
      console_priority: warning
      file_priority: info
    metrics_excess_log: false # Turn to true for debugging
    metrics_filter:
      - exclude: "ma_rabbitmq*"
      - exclude: "rabbitmq*"
    prometheus:
      enabled: false
      interval: 60
      log_errors: true
      max_metrics: 10000
      max_metrics_per_process: 10000
      max_tags_per_metric: 20
      histograms: false
      timeout: 1
      # Filtering processes to scan. Processes not matching a rule will not
      # be scanned
      # If an include rule doesn't contain a port or port_filter in the conf
      # section, we will scan all the ports that a matching process is listening to.
      process_filter:
        - exclude:
            process.name: docker-proxy
        - exclude:
            container.image: sysdig/agent
        # special rule to exclude processes matching configured prometheus appcheck
        - exclude:
            appcheck.match: prometheus
        - include:
            container.label.io.prometheus.scrape: "true"
            conf:
              # Custom path definition
              # If the label doesn't exist we'll still use "/metrics"
              path: "{container.label.io.prometheus.path}"

              # Port definition
              # - If the label exists, only scan the given port.
              # - If it doesn't, use port_filter instead.
              # - If there is no port_filter defined, skip this process
              port: "{container.label.io.prometheus.port}"
              port_filter:
                - exclude: [9092, 9200, 9300]
                - include: 9090-9500
                - include: [9913, 9984, 24231, 42004]
        - exclude:
            container.label.io.prometheus.scrape: "false"
        - include:
            kubernetes.pod.annotation.prometheus.io/scrape: true
            conf:
              host: 127.0.0.1
              path: "{kubernetes.pod.annotation.prometheus.io/path}"
              port: "{kubernetes.pod.annotation.prometheus.io/port}"
        - exclude:
            kubernetes.pod.annotation.prometheus.io/scrape: false
    watchdog:
      max_memory_usage_mb: 2048
      max_memory_usage_subprocesses:
        sdchecks: 256
        sdjagent: 256
        mountedfs_reader: 32
        statsite_forwarder: 32
        cointerface: 2048
    k8s_extra_resources:
      include:
        - services
        - resourcequotas
        - persistentvolumes
        - persistentvolumeclaims
        - horizontalpodautoscalers
secure:
  enabled: false
tolerations:
  - key: nodeclass
    effect: NoSchedule
    operator: Equal
    value: ephemeral
ebpf:
  enabled: false
slim:
  enabled: true
sysdig:
  settings:
    k8s_cluster_name: flex-vol-test
